name: chopper_library
description: Recipe Finder.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.7
  json_annotation: ^4.1.0
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  build_runner: ^2.1.1
  json_serializable: ^4.1.1


flutter:

  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/

